name: Portfolio Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    # Backup current live version (to rollback later if needed)
    - name: Backup Current Website
      run: |
        mkdir backup
        aws s3 sync s3://zintora-soft-project ./backup
        aws s3 sync ./backup s3://zintora-soft-project-backup

    # Deploy new version
    - name: Deploy Static Website to S3
      run: |
        set -e
        aws s3 sync . s3://zintora-soft-project --delete

    # Download logs from S3 logging bucket
    - name: Download S3 Access Logs
      run: |
        mkdir s3-logs
        aws s3 sync s3://zintora-soft-logs/access-logs ./s3-logs --exact-timestamps

    - name: Upload Logs as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: s3-access-logs
        path: s3-logs

    # Rollback if deployment fails
    - name: Rollback on Failure
      if: failure()
      run: |
        echo "Deployment failed! Rolling back..."
        aws s3 sync s3://zintora-soft-project-backup s3://zintora-soft-project --delete

    # (Optional) Send SNS Notification on Failure
    - name: Send Failure Notification
      if: failure()
      run: |
        aws sns publish \
          --topic-arn arn:aws:sns:ap-south-1:123456789012:s3-deploy-alerts \
          --message "Deployment failed and rollback executed for Portfolio website."
