name: Portfolio Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    # Deploy new version (versioning enabled)
    - name: Deploy Static Website to S3
      run: |
        set -e
        aws s3 sync . s3://zintora-soft-project --delete

    # Download logs from S3 logging bucket
    - name: Download S3 Access Logs
      run: |
        mkdir s3-logs
        aws s3 sync s3://zintora-soft-logs ./s3-logs --exact-timestamps

    - name: Upload Logs as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: s3-access-logs
        path: s3-logs

    # Rollback if deployment fails using S3 versioning
    - name: Rollback on Failure
      if: failure()
      run: |
        echo "Deployment failed! Rolling back using S3 versioning..."
        # Get list of object versions before deployment
        aws s3api list-object-versions --bucket zintora-soft-project --output text > version-list.txt
        # For each object, restore the previous version
        awk '/VERSIONS/ {print $3, $4}' version-list.txt | while read key version; do
          aws s3api copy-object \
            --bucket zintora-soft-project \
            --key "$key" \
            --copy-source zintora-soft-project/"$key"?versionId="$version"
        done
